
# ▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀
# 
#  ★ ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗  ★ 
#  ★ ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗ ★ 
#  ★ ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║ ★ 
#  ★ ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║ ★ 
#  ★ ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝ ★ 
#    ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝                 
#
# ▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀

# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# ThinkPad X1 Carbon Gen 8 + Docking Station ThinkPad 40AH135US.

# Configuracion Predeterminada (fallback)
 monitor = ,preferred,auto,1.33

# Monitor principal del laptop ubicado a la izquierda
# monitor = eDP-1, 2560x1440@60, 0x0, 1.67 # Texto mas legible a corta vision
# monitor = eDP-1, 2560x1440@60, 0x0, 1.33 # Equilibrado similar a 1080p con escala 1.25
# monitor = eDP-1, 2560x1440@60, 0x0, 1.25 # Mayor campo visual de lectura similar a 1080p con escala 1

# Monitor 34" QHD Ultrawide 165Hz (derecha)
# Offset X = 2560/1.25 = 2048px (ancho lógico del laptop)
# monitor = DP-4, 3440x1440@165, 2048x0, 1


