
# ▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀
# 
#  ★ ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗  ★ 
#  ★ ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗ ★ 
#  ★ ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║ ★ 
#  ★ ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║ ★ 
#  ★ ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝ ★ 
#    ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝                 
#
# ▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀

# Ｈｙｐｒｌａｎｄ by ✯ 𝓭𝓪𝓷𝓰𝓶𝓸𝔃 

# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# 1. Monitores (Configurados vía monitors.conf)
source = ~/.config/hypr/Modules/monitors.conf

# █▀▀ █▀█ █░░ █▀█ █▀█ █▀
# █▄▄ █▄█ █▄▄ █▄█ █▀▄ ▄█

# Colores del entorno grafico
source = ~/.config/hypr/Modules/colors.conf

# █▀▄ █▀▄ █▀█ █▀▀ █▀█ ▄▀█ █▀▄▀█ █▀
# █▀▀ █▀▄ █▄█ █▄█ █▀▄ █▀█ █░▀░█ ▄█

$terminal = kitty
$fileManager = dolphin 
$menu = rofi -show drun
$browser = chromium
$notepad = kitty
$calculator = galculator
$screenshot = xfce4-screenshooter
$lock = pidof hyprlock || hyprlock
$editor = kitty -e nvim
$terManager = kitty -e ranger
$taskManager = kitty -e glances

# █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

exec-once = dbus-update-activation-environment --systemd --all
exec-once = hyprctl setcursor Breeze_Light 24
exec-once = waybar
exec-once = hypridle
exec-once = mako
exec-once = awww-daemon
exec-once = ~/.config/waybar/Scripts/notification-watcher.sh
exec-once = wlsunset -l 4.6097 -L -74.0817 -t 3000

# █▀▀ █▄░█ █░█
# ██▄ █░▀█ ▀▄▀

#  Environment Variables | Variables de Entorno
source = ~/.config/hypr/Modules/env.conf

# ▄▀█ █▀▀ █▀ ▀█▀ █░█ █▀▀ ▀█▀ █ █▀▀
# █▀█ ██▄ ▄█ ░█░ █▀█ ██▄ ░█░ █ █▄▄

#  Look and Feel (Colores, Animaciones, Sombras)
source = ~/.config/hypr/Modules/appearance.conf

# █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
# █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█

#  Layouts (Capas)
source = ~/.config/hypr/Modules/layout.conf

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
    background_color = $background
}

# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░

#  Entrada y Ajustes 

source = ~/.config/hypr/Modules/input.conf

# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀
# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█

# 7. Atajos de Teclado (Keybindings)
source = ~/.config/hypr/Modules/keybinds.conf

# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

##############################
### WINDOWS AND WORKSPACES ###
##############################

# 8. Reglas de Ventana
source = ~/.config/hypr/Modules/rules.conf

# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule {
    name = blur_with_ignore_alpha
    match:namespace = ^(walker|notifications|swayosd|waybar)$
    blur = true
    ignore_alpha = 0.1
}
xwayland {
    force_zero_scaling = true
}

# Disable Update Box News
ecosystem:no_update_news = true

# ✯ ♱ 𝔡𝔞𝔫𝔤𝔪0𝖟 ♱ ✯