
# ▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀
# 
#  ★ ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗  ★ 
#  ★ ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗ ★ 
#  ★ ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║ ★ 
#  ★ ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║ ★ 
#  ★ ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝ ★ 
#    ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝                 
#
# ▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀

# Ｈｙｐｒｌａｎｄ by ✯ 𝓭𝓪𝓷𝓰𝓶𝓸𝔃 

# █▀█ ▄▀█ ▀█▀ ▀█▀ █▀▀ █▀█ █▄░█   █▀▀ █▀█ █░░ █▀█ █▀█ █▀
# █▀▀ █▀█ ░█░ ░█░ ██▄ █▀▄ █░▀█   █▄▄ █▄█ █▄▄ █▄█ █▀▄ ▄█

$background = rgba(262626ff)
$surface = rgba(404040ff)
$foreground = rgba(e6e6e6ff)
$shadow_color = rgba(00000066)
$active_border_color = rgb(00ccff) rgb(0055ff) 45deg
$inactive_border_color = rgba(00ccff66) rgba(0055ff66) 45deg

#More accent

#$accent_green = rgba(66cc66ff)
#$accent_yellow = rgba(ffcc66ff)
#$accent_blue = rgba(6699ffff)
#$accent_magenta = rgba(cc66ccff)
#$accent_cyan = rgba(66ccccff)